import "D:\Program Files\Microsoft Visual Studio .NET 2003\SDK\v1.1\include\corsym.idl";
import "D:\Program Files\Microsoft Visual Studio .NET 2003\SDK\v1.1\include\corprof.idl";
import "docobj.idl";


[ version(0.1), uuid(03671C9F-E46B-4E79-BE3E-4E07EE6749CB), helpstring("PartCover module") ]
library PartCover
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		uuid(9BC23D20-04DE-4ee7-AB24-1E890C741F78),
		helpstring("CorDriver.IPartCoverConnector interface"),
		custom(8AFCDA7F-33B7-3120-86A8-754D2C0C0578, "library_block")
	] 
#line 46 "e:\\temp\\partcover\\partcover.cordriver\\interface.h"
	enum ProfilerMode {
		COUNT_COVERAGE = 1,
		COVERAGE_USE_CLASS_LEVEL = 4,
		COVERAGE_USE_ASSEMBLY_LEVEL = 8,
	};

	[
		object,
		uuid(4BAD004E-1EF9-43d2-8D3A-095963E324EF),
		helpstring("CorDriver.IInstrumentedBlockWalker interface"),
		custom(8AFCDA7F-33B7-3120-86A8-754D2C0C0578, "library_block")
	] 
#line 61 "e:\\temp\\partcover\\partcover.cordriver\\interface.h"
	interface IInstrumentedBlockWalker : IUnknown {
		HRESULT  BeginReport();
#line 64 "e:\\temp\\partcover\\partcover.cordriver\\interface.h"
		HRESULT  EnterTypedef([in]BSTR assemblyName, [in]BSTR typedefName, [in]DWORD flags);
		HRESULT  EnterMethod([in]BSTR methodName, [in]BSTR methodSig, [in]DWORD flags, [in]DWORD implFlags);
		HRESULT  MethodBlock([in]ULONG position, [in]ULONG blockLen, [in]DWORD visitCount, [in]ULONG32 fileId, [in]ULONG32 startLine, [in]ULONG32 startColumn, [in]ULONG32 endLine, [in]ULONG32 endColumn);
		HRESULT  LeaveMethod();
		HRESULT  LeaveTypedef();
#line 70 "e:\\temp\\partcover\\partcover.cordriver\\interface.h"
		HRESULT  RegisterFile([in]ULONG32 fileId, [in]BSTR fileUrl);
		HRESULT  EndReport();
	};

	[
		uuid(5B8DF888-1698-4164-84BF-DDE1A15FF5D4),
		helpstring("CorDriver.CallReason  enum"),
		custom(8AFCDA7F-33B7-3120-86A8-754D2C0C0578, "library_block")
	] 
#line 24 "e:\\temp\\partcover\\partcover.cordriver\\callgatherer.h"
	enum CallReason {
		eEnter = 0,
		eLeave = 1,
		eTailcall = 2,
	};

	[
		uuid(89FC4679-2C1E-439d-A9E1-56B817C4C656),
		helpstring("CorDriver.CorProfiler Class"),
		version(0.1)
	] 
#line 12 "e:\\temp\\partcover\\partcover.cordriver\\corprofiler.h"
	coclass CorProfiler {
		[default] interface IUnknown;
	};

	[
		object,
		uuid(AF8D2B08-1DDF-4AE5-986C-09EDD8326045),
		helpstring("CorDriver.IPartCoverConnector interface"),
		custom(8AFCDA7F-33B7-3120-86A8-754D2C0C0578, "library_block")
	] 
#line 15 "e:\\temp\\partcover\\partcover.cordriver\\partcoverconnector.h"
	interface IPartCoverConnector : IUnknown {
		HRESULT  StartTarget([in] BSTR targetPath, [in] BSTR targetWorkingDir, [in] BSTR targetArguments, [in] VARIANT_BOOL redirectOutput);
		HRESULT  SetVerbose([in] INT logLevel);
		HRESULT  EnableOption([in] enum ProfilerMode mode);
		HRESULT  WaitForResults([in] VARIANT_BOOL delayClose);
		HRESULT  CloseTarget();
#line 24 "e:\\temp\\partcover\\partcover.cordriver\\partcoverconnector.h"
		HRESULT  WalkInstrumentedResults([in] IInstrumentedBlockWalker *walker);
#line 26 "e:\\temp\\partcover\\partcover.cordriver\\partcoverconnector.h"
		HRESULT  IncludeItem([in] BSTR item);
		HRESULT  ExcludeItem([in] BSTR item);
	};

	[
		uuid(15225ABF-81EE-4351-B336-AB38E5B95FD7),
		helpstring("CorDriver.PartCoverConnector Class"),
		version(0.1)
	] 
#line 39 "e:\\temp\\partcover\\partcover.cordriver\\partcoverconnector.h"
	coclass PartCoverConnector {
		interface IPartCoverConnector;
	};

}

