//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartCover.Browser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 9.75pt")]
        public global::System.Drawing.Font ViewPaneFont {
            get {
                return ((global::System.Drawing.Font)(this["ViewPaneFont"]));
            }
            set {
                this["ViewPaneFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("239, 239, 228")]
        public global::System.Drawing.Color ViewPaneBackground {
            get {
                return ((global::System.Drawing.Color)(this["ViewPaneBackground"]));
            }
            set {
                this["ViewPaneBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ViewPaneForeground {
            get {
                return ((global::System.Drawing.Color)(this["ViewPaneForeground"]));
            }
            set {
                this["ViewPaneForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 255, 200")]
        public global::System.Drawing.Color ViewPaneCoveredBlockBackroung {
            get {
                return ((global::System.Drawing.Color)(this["ViewPaneCoveredBlockBackroung"]));
            }
            set {
                this["ViewPaneCoveredBlockBackroung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 200, 200")]
        public global::System.Drawing.Color ViewPaneUncoveredBlockBackroung {
            get {
                return ((global::System.Drawing.Color)(this["ViewPaneUncoveredBlockBackroung"]));
            }
            set {
                this["ViewPaneUncoveredBlockBackroung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ByName")]
        public string VolumeTreeMethodSort {
            get {
                return ((string)(this["VolumeTreeMethodSort"]));
            }
            set {
                this["VolumeTreeMethodSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HighlightAllFile {
            get {
                return ((bool)(this["HighlightAllFile"]));
            }
            set {
                this["HighlightAllFile"] = value;
            }
        }
    }
}
